services:
  postgres:
    container_name: postgres-docker
    # image: postgres
    build:
      context: ./postgres
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=$(POSTGRES_DB)
    volumes:
      - ${DATA_LIB}/data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    # volumes:
    #   - ${DATA_LIB}/data/postgres:/var/lib/postgresql/data
    #   - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # networks:
    #   - leal-network

  # php8:
  #   build:
  #     context: ./php8
  #     args:
  #       - USER_UID=${USER_UID}
  #       - USER_GID=${USER_GID}
  #   container_name: leal-php8
  #   restart: always
  #   volumes:
  #     - ../:/var/www/
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
  #     - ./openssl.cnf:/etc/ssl/openssl.cnf
  #   networks:
  #     - leal-network
  #   tty: true

  # nginx:
  #   build: ./nginx
  #   container_name: leal-nginx
  #   restart: always
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "6001:6001"
  #   volumes:
  #     - ../:/var/www/
  #     - ./nginx/sites/:/etc/nginx/conf.d/
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #   networks:
  #     - leal-network
  #   depends_on:
  #     - php8

  # mariadb:
  #   image: mariadb:latest
  #   command: mariadb --sql_mode=""
  #   container_name: leal-mariadb
  #   restart: always
  #   tty: true
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  #     - MARIADB_USER=${MARIADB_USER}
  #     - MARIADB_PASSWORD=${MARIADB_PASSWORD}
  #   volumes:
  #     - ${DATA_LIB}/data/mysql:/var/lib/mysql
  #     - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - leal-network
      
  # node:
  #   build:
  #     context: ./node
  #     args:
  #       - USER_UID=${USER_UID}
  #       - USER_GID=${USER_GID}
  #   container_name: leal-node
  #   restart: always
  #   volumes:
  #     - ../:/var/www/
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - ./openssl.cnf:/etc/ssl/openssl.cnf
  #     - "./node/ecosystem.config.js:/tmp/ecosystem.config.js"
  #   networks:
  #     - leal-network
  #   tty: true
  #   depends_on:
  #     - workspace

  # workspace:
  #   build:
  #     context: ./workspace
  #     args:
  #       - USER_UID=${USER_UID}
  #       - USER_GID=${USER_GID}
  #   container_name: leal-workspace
  #   restart: always
  #   volumes:
  #     - ../:/var/www/
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - ./openssl.cnf:/etc/ssl/openssl.cnf
  #   networks:
  #     - leal-network
  #   tty: true

  caddy:
    build: ./caddy
    volumes:
      - ../:/var/www
      - ./caddy/caddy:/etc/caddy
      - .logs/caddy:/var/log/caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network
    restart: always
    tty: true  

networks: 
  docker-network:
    driver: bridge